### ISSUE TITLE
Nuxt Page Transition

### ISSUE THREAD

**Issue by Lahori-Jawan** [mattrothenberg/vue-overdrive#1]
Can I Use it with Nuxt? especially page transition.... if yes then an example would be great!!!

**Comment by mattrothenberg** [comment]
Hey @Lahori-Jawan, good question!

Have you tried using it with Nuxt yet? I'm honestly not sure if it'll work or not.

**Comment by cannap** [comment]
https://nuxt-overload-test.glitch.me this works but i did not test with page transitions

**Comment by mattrothenberg** [comment]
Bravo @cannap! Feel free to send a PR adding that example to the README
