### ISSUE TITLE
Position: Fixed instead of Absolute.

### ISSUE THREAD

**Issue by jamesblasco** [mattrothenberg/vue-overdrive#10]
First of all, thank you very much for this great contribution. Vue-overdrive is really great.

I have had several problems when the child of the overdrive component has an absolute position with respect to his father instead of the body. 

I fixed it by changing that the cloned element has a fixed position and not an absolute

 ```js
 getPosition (addOffset = false) {
        const node = this.$el.firstChild
        const rect = node.getBoundingClientRect()
        const computedStyle = getComputedStyle(node)
        const marginTop = parseInt(computedStyle.marginTop, 10)
        const marginLeft = parseInt(computedStyle.marginLeft, 10)
        return {
          top: (rect.top - marginTop) + ((addOffset ? 1 : 0) * (window.pageYOffset || document.documentElement.scrollTop)) + 'px',
          left: (rect.left - marginLeft) + 'px',
          width: rect.width + 'px',
          height: rect.height + 'px',
          margin: computedStyle.margin,
          padding: computedStyle.padding,
          borderRadius: computedStyle.borderRadius,
          position: 'fixed'
        }
 }

```

**Comment by mattrothenberg** [comment]
Could you please provide a CodeSandbox that reproduces your issue with
absolutely positioned elements?

Thanks!

**Comment by jamesblasco** [comment]
I will try (I am not used to CodeSandBox and I don´t know how to add vuejs and vueoverdrive.
