### ISSUE TITLE
Wrong position and skewing images at the first click

### ISSUE THREAD

**Issue by gregorvoinov** [mattrothenberg/vue-overdrive#11]
hi,

I tried out your vue-overdrive, but I'm running in some problems... 
I have done a [screen-record ](https://www.useloom.com/share/ff3bb771e34e47819ffeea1cb3e518bb )where you can see the behavior. At the first click it doesn't work really. Starts transitions from the wrong place and skew the images if i go back in the overview list. I use the same images in the overview page and in the detailpage, so it can't be a loading problem because the image should be in the cache...

I have also done a sandbox, maybe you can take a look if its my failure or its really an issue ;) 
https://codesandbox.io/s/vvq286qjpy

## Specifications

  - Version: latest
  - Platform: windows/mac

**Comment by gregorvoinov** [comment]
wow thank you man ;) that helped me a lot ;)

I updated my sandbox [there](https://codesandbox.io/s/ym0221wq39), but now i have the behavior that it fades first out all elements and then fades in the shared transition element.

If I remove overdrive from the markup then there is no fading (and of course no animation ;)

I've seen that on the elements the style opacity: 1 is set, but I do not put this by myself, maybe it has something to do with that behavior?

![image](https://user-images.githubusercontent.com/9499590/50182613-15b42b80-0310-11e9-86c4-e07f238a0ebf.png)

**Comment by mattrothenberg** [comment]
@gregorvoinov Glad it helped.

The opacity thing is interesting. `overdrive` certainly doesn't do anything explicitly with opacity, but i know that [Ramjet](https://github.com/Rich-Harris/ramjet) (the library I'm using under the hood) does.

**Comment by gregorvoinov** [comment]
Thank you for your effort.

So you have no idea how to get over this problem? Then I will try my luck at ramjet.

**Comment by mattrothenberg** [comment]
I'll keep investigating.

**Comment by gregorvoinov** [comment]
thank you, I also started at ramjet an [issue](https://github.com/Rich-Harris/ramjet/issues/56)

**Comment by mattrothenberg** [comment]
@gregorvoinov I just published an alpha release that hopefully resolves your issue: https://www.npmjs.com/package/vue-overdrive/v/1.0.0-0

Would you mind bumping versions and letting me know if it works?

Merry Xmas 🎄

**Comment by gregorvoinov** [comment]
But why is this behavior only if I go back? I know if I'm scrolling I have also to check my scrollposition and do some offset if I scroll the page, but one problem after another ;) So if I don't scroll and just click the first image everything is fine, now click the browser back or the link button (don't scroll) than the image jumps and not the whole view (the home headline doesn't jump).

**Comment by mattrothenberg** [comment]
Eek, I'm not sure I fully understand the issue you're describing. I'm able to create _fairly_ smooth image transitions, though this is starting to sound like an edge-case of this library (one that I don't feel is super important to support at the moment).

https://streamable.com/0ft71

If you're up for a a challenge, I welcome any and all pull-requests that would tweak the library to your liking. Until then, I'm confident we can mark this issue as "resolved."

As an alternative, you might want to check out https://fancyapps.com/fancybox/3/ which does this effect pretty well.
