### ISSUE TITLE
Error in production build (v1.0.0)

### ISSUE THREAD

**Issue by mornir** [mattrothenberg/vue-overdrive#15]
After upgrading to v.1.0.0, I get the following error in the production build:
```
overdrive.js:1 Uncaught ReferenceError: parcelRequire is not defined
    at Object.d986 (overdrive.js:1)
    at a (bootstrap:78)
    at Module.56d7 (MovieDetails.vue?5d95:1)
    at a (bootstrap:78)
    at Object.0 (bootstrap:151)
    at a (bootstrap:78)
    at r (bootstrap:45)
    at bootstrap:151
    at bootstrap:151
```
The app is working fine with `npm run serve`.
Here is the repo: https://github.com/mornir/vue-movies (I downgraded back to v0.0.12)

Note: I'm using the modern build and I am not transpiling with Babel.

**Comment by mattrothenberg** [comment]
Ugh, this isn't the first issue reported about Parcel.

I might try to use plain old Webpack and see if that resolves the issue.

**Comment by mattrothenberg** [comment]
@mornir Take a look at https://github.com/mattrothenberg/vue-overdrive/pull/16 and let me know if you think this might help.

**Comment by mornir** [comment]
What would be the best way to try your pull request in my project?
I merged it to my forked repo (https://github.com/mornir/vue-overdrive), but I don't see how I can add it to my project... I tried fiddling with the folder in node_modules, but to no avail.

**Comment by mattrothenberg** [comment]
You could always paste the minified JS into your project, import that file instead of the package from NPM, and see if it throws an error on build.
________________________________

**Comment by mornir** [comment]
Do you mean like this https://github.com/mornir/vue-movies/commit/ce4cf99f705e8ad83d96330193a534cbef2089bb ?

It doesn't throw an error on build, but `vue-overdrive` doesn't work anymore.

**Comment by mattrothenberg** [comment]
@mornir Weird, I figured that would have worked. Looks like that bundle is messed up. Feel free to fork/re-configure that Webpack config to get it to work.

Nothing special is happening as part of the build process. The sole dependency is `ramjet`, and we spit out a minified JS file.

I'll investigate when I have some time this week.

**Comment by mattrothenberg** [comment]
@mornir Closed by https://github.com/mattrothenberg/vue-overdrive/issues/18.

Cutting a build (`1.2.0`) which should resolve this.

**Comment by mornir** [comment]
Yep, problem solved 👌
