### ISSUE TITLE
Animation not runnig after animated first element  

### ISSUE THREAD

**Issue by dimti** [mattrothenberg/vue-overdrive#17]
## Expected Behavior
Animation on all elements

## Actual Behavior
First element - animation OK
Two element - not animated, elements changed without animation

## Steps to Reproduce the Problem
Vue template:

    <template>
    <div class="">

                <overdrive key="a2" id="window2" :duration="900" v-if="!windowOpen2">
                    <div key="a22" style="color:green;" @click="windowOpen2=!windowOpen2">
                        bbbbbbbbbbbbbbbbbb
                    </div>
                </overdrive>
                <overdrive key="a1" id="window" :duration="900" v-if="!windowOpen">
                    <div key="a11" style="color:green;" @click="windowOpen=!windowOpen">
                        2222222222222222222
                    </div>
                </overdrive>
        <br><br>
                <hr>
        <br><br>
                <overdrive key="b1" id="window" :duration="900" v-if="windowOpen">
                    <div key="b11" style="color:green;" @click="windowOpen=!windowOpen">
                        1111111111111111111
                    </div>
                </overdrive>
                <overdrive key="b2" id="window2" :duration="900" v-if="windowOpen2">
                    <div key="b22" style="color:green;" @click="windowOpen2=!windowOpen2">
                        aaaaaaaaaaaaaaaaaaa
                    </div>
                </overdrive>

    </div>
    </template>

    <script>
    //    import * as easing from 'eases/quart-in-out';
    //
    export default {
    name: 'inscription-step-one',
    data() {
        return {
            windowOpen: true,
            windowOpen2: true,
            windowOpen3: true,
        };
    },
    };
    </script>

Trouble with animation two or more elements: http://wpstudio.ru:8000/f/0dcadb381e814e99a913/

Without any css and unstable javascript-libs and clear html:
http://wpstudio.ru:8000/f/69c040abb8254cbc9601/

## Specifications

  - Version: 1.0.0
  - Platform: Arch Linux, Debian, node v8.9.3, v10.11.0

**Comment by mattrothenberg** [comment]
Good catch, I'll look into this as soon as I can 👍

**Comment by mattrothenberg** [comment]
@dimti I'm hopeful that the latest version fixed the issue 🤞😁

Is this kind of what you were going for?

![kapture 2019-01-26 at 16 06 06](https://user-images.githubusercontent.com/5148596/51792780-6119ef00-2184-11e9-8fb6-048d6f11f0cf.gif)

**Comment by dimti** [comment]
Last update fixed this. Ok.
