### ISSUE TITLE
"Critical dependency: the request of a dependency is an expression" when running the app

### ISSUE THREAD

**Issue by drank** [mattrothenberg/vue-overdrive#18]
Hi,

I am pretty new to Vue.js so please bear with me.

I installed vue-overdrive and configured it for 2 elements. When I reload my app, the following is displayed in the console:

```
[WDS] Warnings while compiling.
./node_modules/vue-overdrive/dist/overdrive.js 1:290-294
Critical dependency: the request of a dependency is an expression
```
The animation works OK, only this warning is bothering me. Is this something that I need to worry and can I configure something so that the warning goes away?

## Specifications

  - Version: Vue.js v2.6.7, Webpack v4.29.5
  - Platform: Win 7 64-bit
  - Subsystem:

**Comment by mattrothenberg** [comment]
Sounds related to https://github.com/mattrothenberg/vue-overdrive/issues/15.

I'll do some investigation.

**Comment by drank** [comment]
Thank you!

**Comment by mattrothenberg** [comment]
@drank Can you please try the following branch: https://github.com/mattrothenberg/vue-overdrive/tree/parcel-to-rollup?

I'd recommend cloning that to somewhere on your machine and doing the following.

```
$ yarn
$ yarn build
$ yarn link
```
Then, in the Vue project that you're working on, go ahead and remove `vue-ovedrive` from its `package.json`, remove `yarn.lock`, and then re-run `yarn`. To use the linked package, run `yarn link vue-overdrive` and spin up your app as normal.

If that resolves the issue, let me know.

**Comment by drank** [comment]
Hi @mattrothenberg 

I did exactly as you instructed but when running `yarn run dev` in my project I got this error:

```
ERROR  Failed to compile with 1 errors

This dependency was not found:
* ramjet in ./node_modules/babel-loader/lib??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/TheFiltersPanel.vue?vue&type=script&lang=js&
To install it, you can run: npm install --save ramjet
```

Is ramjet also removed when I removed vue-overdrive from package.json? Do I just go ahead and install ramjet?

**Comment by mattrothenberg** [comment]
Hmm, that doesn't make any sense. Is your project on GitHub by an chance?

**Comment by drank** [comment]
Sorry, my bad - I was having an `import * as ramjet from 'ramjet'` statement in my code (using some easing functions different from the default one). I commented that code and run the project.

There are no more warnings now, so it seems your fix works. Thank you!

Do I now unlink the downloaded project and wait for an update?

**Comment by mattrothenberg** [comment]
No worries. 

Go ahead and unlink the downloaded project, and now let's verify this works with the newly published package. I've gone ahead and released a build on the `next` tag.

`yarn add vue-overdrive@next`

Give that a whirl, and let me know if everything works as you expect.

**Comment by drank** [comment]
Yes, now it works perfectly! Thank you very much!

**Comment by mattrothenberg** [comment]
@drank Cool. I'll cut a `minor` build now (`1.2.0`). You can upgrade at your leisure.
