### ISSUE TITLE
The first two animations after app reload do not morph one element into another

### ISSUE THREAD

**Issue by drank** [mattrothenberg/vue-overdrive#20]
Hi,

I have the following (simplified) code:
```
<q-list v-if="displayFiltersTree" key="filtersTree">
  <overdrive v-for="filter in filters" :key="filter.id + '-a'" :id="filter.id" :duration="1500">
    <h-filter />
  </overdrive>
</q-list>
<q-list v-else key="addedFilters">
  <overdrive v-for="filter in filters" :key="filter.id + '-b'" :id="filter.id" :duration="1500">
    <h-filter />
  </overdrive>
</q-list>
```
where "h-filter" is a custom component.

Please refer to the following video I made: https://www.dropbox.com/s/xqn19tt1yi70u1h/2019-03-09%2018-37-29.flv?dl=0

When I click on the input field I want the displayed "Periods" filter to morph into the same "Periods" filter which is displayed in the list that is shown upon clicking in the input box. The 2 filters are the same objects (if that matters).
You can see that on the initial click that there is no transition between the 2 elements but the filter is coming from somewhere on the upper-right side. Same thing happens when warping back the 1st time.
All the subsequent animations work exactly how I want them but only the 1st two are behaving strangely.

Am I doing something wrong or maybe I am missing something?

**Comment by mattrothenberg** [comment]
I'll look at this code later. I'm not sure I totally understand what you're
going for here design wise, though.

The sky is the limit, but I feel like Overdrive (and Ramjet, by extension)
lends itself to simpler animations (think images and shapes).

**Comment by drank** [comment]
The idea is that the 1st "Periods" filter morphs into the position of the 2nd one (the one that is displayed when clicking into the input box). The problem is that this transition happens properly only on the 2nd click in the input box, after the app has been loaded. The 1st animation is always "skewed", i.e. the element comes from some position that is NOT the position of the 1st element.

In fact, the setup is not so complicated - I have a v-if with a v-else and two overdrives that wrap the same component - pretty much the same as your example on the README.md (at the bottom).

Please check the video, it shows the problem - pay attention to the 1st click in the input box and how the "Periods" element if animated after this click and then - how it is animated on subsequent clicks.
