### ISSUE TITLE
How can this be used to animate from a blog post excerpt to a full page single post view?

### ISSUE THREAD

**Issue by zachwright** [mattrothenberg/vue-overdrive#21]
I have a Nuxt app that has a v-for loop populating a "grid" of blog posts like on a typical blog page. The intended animation is to click on any post and have it morph from the small square-ish excerpt preview in the grid into the full page view. (Different routes - i.e. /blog and /blog/blog-post-title-here) 

I am trying to utilize ideas from this solution here: https://glitch.com/edit/#!/nuxt-overload-test?path=pages/about.vue:2:42

However, I think I am getting issues regarding each post in the grid having the same overdrive id tag:

*(pseudocode)*
```
v-for {
<overdrive id="element">
    <Post />
</overdrive>
}
```

Do you know if this tool can be used to achieve the effect I am trying for?

**Comment by mattrothenberg** [comment]
Conceptually it could work. To be totally honest with you, I've learned from creating/maintaining this library that web animation is _hard_ to get right.

Technically, I think your implementation is close, but not quite there. For each iteration of your `v-for`, you would render an instance of `<Overdrive />` where the ID is a unique identifier. If your posts have IDs, for example, you might do something like.

```html
<div v-for="post in posts">
  <overdrive :id="post.id">
    <div>thing</div>
  </overdrive>
</div>
```
Let me know if that helps!

**Comment by zachwright** [comment]
Thank you, that actually helped a lot. That was actually a pretty obvious solution I'm embarrassed I didn't think of before posting. 

I'll try to read through your examples and source code a little more to see if I can find some more answers to some of the animation problems I'm still having. 

Thanks for your time and help!

**Comment by mattrothenberg** [comment]
@zachwright Don't sweat it 😄 

Happy to help further. Feel free to open another issue if a specific question arises.

Cheers!
