### ISSUE TITLE
Elements are "shifting" into place at end of animation and on page load.

### ISSUE THREAD

**Issue by zachwright** [mattrothenberg/vue-overdrive#22]
In this video I recorded the blog items kind of "shifting" downward at the end of the animation time frame: https://youtu.be/87C7tMdD71w 

Specifically, the unintended effects are 
* When a grid item expands to the full page, it animates then shifts downward suddenly at the end of the animation.
* When a full page post animates back into the grid, all of the grid items "wait" above the correct location and then "shift" downwards at the end of the animation.
* On page loads, every blog post seems to either animate from the bottom left of the screen if you refresh on the blog page.
* If you navigate to the blog page after the app has started, all the blog posts do the shift downwards. 

The blog is implemented in the way we discussed in issue #21.

I successfully implemented two pages (in nuxt in this same app) called square and circle that transform a circle to a square (kind of like the examples given). It seems to be an issue specifically with my grid posts. I tried hardcoding the post data instead of using the store and I tried swapping the image tags with just divs with a background and they still seem to do the shifting motion. 

Do you have any ideas why the shifting would be occurring? My thoughts first suspect something with the v-for loop and every blog post having an overdrive tag added to it, but I'm not sure where to go from there.

```
// Post.vue
<div class="post">
       
          <nuxt-link v-on:click.native="setCurrentPost" :to="{path: id, params: {id: id}}">
           
            <overdrive :id="'animate-' + id" :easing="easing" :duration="700" >
              <img class="thumbnail" :class="{expanded : expanded}" :src="image" alt="">
            </overdrive>
            <h2> {{ title }}</h2>
            <p>By: {{`${authorFirst} ${authorLast}`}}</p>
            <p> {{date}}</p>
            <p class="summary">{{summary}}</p>
          </nuxt-link>

    </div>
```

```
// Posts.vue
 <div class="row">
      <div class="post-wrapper" v-for="post in posts.slice(0,10)" v-bind:key="post.id">
        
          <Post :id="post.id" :title="post.title" :image="post.image" :authorFirst="post.author.first_name" :authorLast="post.author.last_name" :date="post.date_modified" :summary="post.summary" />
       
  </div>
</div>
```
```
// /blog/_id.vue (single page view of post)
<div>
 


    <div class="close">
      <nuxt-link to="/blog">
        <span class="x">X</span>
      </nuxt-link>
      
    </div>
    <div class="post-wrap">
      <overdrive :id="'animate-' + currentPost[0].id" :easing="easing" :duration="700" @animation-end="handleAnimationEnd">
        <!--<div class="featured-image" :style="{ backgroundImage: 'url(' + currentPost[0].image + ')' }"></div>-->
        <img class="featured-image" :src="currentPost[0].image" alt="">
      </overdrive>
      <transition appear>
        <div class="post-content">
          <h1>{{currentPost[0].title}}</h1>
          <p>{{currentPost[0].date_modified}}</p>
          <div v-html="currentPost[0].content_html"></div>
        </div>
      </transition>

    </div>

   
</div>
```

**Comment by zachwright** [comment]
Does it have to do with elements being removed from the DOM during the animation?

**Comment by mattrothenberg** [comment]
My first guess is that this is happening because you're using images without explicit heights. When the browser loads the page, the images have no height. When they load in, the browser repaints and causes the jank that you see in your YouTube video. 

As an experiment, try putting divs with hard-coded heights in the `<overdrive>` on your index view. Do the same for the detail view. My guess is it will behave normally.

**Comment by mattrothenberg** [comment]
@zachwright, for example:

![Kapture 2019-04-08 at 17 54 16](https://user-images.githubusercontent.com/5148596/55759485-71253900-5a27-11e9-8be1-341b17f5d540.gif)

**Comment by zachwright** [comment]
Would you be able to send me the code that goes with that gif? I'm wondering if I have spaghetti code in my components that are causing weird interactions. I tried setting explicit heights like you said and it still seems to have the same issue. It's clear that the concept should work with the gif you provided though.

**Comment by mattrothenberg** [comment]
https://github.com/mattrothenberg/overdrive-example

**Comment by zachwright** [comment]
Thanks for the code example.

With this code:
```
// /grid/index.vue (equivalent to your Home.vue)
<template>
  <div class="grid">
    <overdrive :id="post" v-for="post in posts" :key="post" duration="700">
      <nuxt-link :to="`grid/${post}`">
        <div class="post"></div>
      </nuxt-link>
    </overdrive>
  </div>
</template>

<script>

export default {
  data() {
    return {
      posts: ["foo", "bar", "baz"]
    }
  }
}
</script>

<style scoped>
.grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  grid-gap: 16px;
  /* padding added to see if jumping still happens */
  padding-top: 200px;
  padding-bottom: 400px;
}
.post {
  height: 300px;
  background: #ccc;
  z-index: 0;
}
</style>
```
```
// /blog/_id.vue (equivalent to your Detail.vue)
<template>
  <div style="padding-bottom: 400px;">
    {{ id }}
    <overdrive :id="id" duration="700">
      <nuxt-link to="/grid">
        <div class="featured-image"></div>
      </nuxt-link>

    </overdrive>
  </div>
</template>

<script>
export default {
  data: () => {
    return {}
  },
  computed: {
    id() {
      return this.$route.params.id
    }
  }
}
</script>

<style scoped>
.featured-image {
  width: 100%;
  height: 600px;
  background: #222;
}
</style>

```

this is the following experience: 
![Kapture 2019-04-08 at 17 59 25](https://user-images.githubusercontent.com/28732225/55762343-340d7680-5a28-11e9-8a17-06ade8a84a97.gif)


I'm beginning to suspect a compatibility issue with Nuxt.js, maybe. It seems to be one of the biggest differences in our code examples is that you are using Vue and I am using Nuxt over top of Vue. 

Thank you for your time and resources thus far figuring this out with me. Do you have any further ideas what else it could be?

**Comment by mattrothenberg** [comment]
I don't think it's a compatibility issue, I think it's code related. I'll
mockup a nuxt example tonight

**Comment by zachwright** [comment]
I was able to start a fresh Nuxt app and use your code and see it working properly. So, it is very clearly something I am doing in my actual app. I'm still unsure what the culprit is, but it is clear this is an issue on my end. 

I apologize for taking up so much of your time and I appreciate you taking the time to help illustrate how to integrate it with Nuxt. 

I will try to determine what I'm doing wrong in my other app to see if it is a potentially common mistake other users of Nuxt and Overdrive might run into and maybe it can help future users.

**Comment by mattrothenberg** [comment]
Roger that! Thanks ❤️

**Comment by mattrothenberg** [comment]
Things should not be animating on page load, this sounds like an incorrect
usage of the library or a new bug altogether.

Please open a new issue with code samples, since this particular issue was
user error.

Thanks

**Comment by zachwright** [comment]
@ThomasKuhlmann I have not figured out that particular issue, yet. I'll try to either open a new issue and/or update here if I discover it to seem to be a bug or just a common pattern issue. 

I DID however notice that some of my "shifting down" problem was caused by having a margin-top on the wrapper div. I'm not sure why, but removing it seemed to stop it from shifting down.
