### ISSUE TITLE
Conflict with Bulma css framework causes shuffling

### ISSUE THREAD

**Issue by philippeluickx** [mattrothenberg/vue-overdrive#9]
## Expected Behavior
Smooth animations

## Actual Behavior
Objects are shuffled after animation.

## Steps to Reproduce the Problem
Using the libraries example:

1. For visual aid, draw boxes around the clickable items in LibraryIndex

```html
<template>
  <div class="flex items-center justify-center h-full">
    <ul class="list-reset">
      <li class="inline-block mr-8" v-for="(library, index) in libraries" :key="index">
        <overdrive :id="library.slug" :duration="3000">
          <router-link :to="calcLink(library)" class="block">
            <div class="foobar">
            <h1>{{ library.name }}</h1>
            </div>
          </router-link>
        </overdrive>
      </li>
    </ul>
  </div>
</template>

<script>
import { mapState } from 'vuex'
export default {
  name: 'character-index',
  data () {
    return {
      characters: []
    }
  },
  methods: {
    calcLink (library) {
      return `/libraries/${library.slug}`
    },
    calcBackground (library) {
      return {
        backgroundImage: `url(/static/${library.image})`
      }
    }
  },
  computed: {
    ...mapState(['libraries'])
  }
}
</script>

<style scoped>
  .wrap {
    width: 768px;
    margin: 0 auto;
  }
  
  .lib-tile {
    background-size: 70%;
    background-position: center center;
    background-repeat: no-repeat;
  }
  .foobar {
    border: 2px solid black;
    background-color: white;
    padding: 3rem;
  }
</style>
```

2. Try out: everything works!
3. Add the Bulma framework in (e.g. cdn). We are not even using any of the classes explicitely.
```
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.css">
```
4: Try out: shuffling...

## Specifications

  - Version: 0.0.12
  - Platform: Chrome, Ubuntu

## Sorry
I know that Bulma is not your library and it might be really hard to start debugging this. But personally, I don't even know where to start.
Let me know if I can be of any help

## Screencast

Without Bulma
![peek 2018-04-22 21-35](https://user-images.githubusercontent.com/836866/39098556-43dbc32c-4675-11e8-88f6-1e30f3f54595.gif)

With Bulma
![peek 2018-04-22 21-34](https://user-images.githubusercontent.com/836866/39098558-474524cc-4675-11e8-8094-00410ad1473a.gif)

**Comment by mattrothenberg** [comment]
As you mention, this issue really falls outside the scope of support that I
feel comfortable providing.

Since the issue manifests upon adding Bulma CSS, the best place to start
looking is indeed the Bulma stylesheet. Is this stylesheet applying global
styles or defaults that are throwing off alignment? Does the issue manifest
if you use Bulma specific components? Etcetera.

Good luck!
